const STATIC_TEXT = {
  GENERIC_ERROR_MESSAGE: "Something went wrong!",
};

const API_STATUS_CODES = {
  // 2xx
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,

  // 4xx
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  TOO_MANY_REQUESTS: 429,

  // 5xx
  INTERNAL_SERVER_ERROR: 500,
};

const SPLIT_TYPES = {
  EVENLY: 0,
  SHARES: 1,
  PERCENTAGE: 2,
  AMOUNT: 3,
};

export { STATIC_TEXT, API_STATUS_CODES, SPLIT_TYPES };
